In [1]:
import cv2
import numpy

In [2]:
face_cascade = cv2.CascadeClassifier('haarcascade_eye.xml') 

In [3]:
# img = cv2.imread('boys.jpg')
cap = cv2.VideoCapture(0)

In [5]:
while True:
    ret,img = cap.read()
    faces = face_cascade.detectMultiScale(img)


    print(faces)

    for (x, y, w, h)in faces:
        cv2.rectangle(img, (x,y), (x+w,y+h), (255,0,0),3)

    cv2.imshow('img1', img)
    if cv2.waitKey(1)==27:
        break

[[256 239  74  74]]
()
[[264 245  51  51]]
[[253 241  63  63]
 [270 243  48  48]]
[[296 234  47  47]]
[[295 235  53  53]
 [274 238  56  56]]
[[274 240  57  57]
 [298 236  50  50]]
[[300 240  48  48]]
[[300 240  49  49]]
[[303 246  44  44]]
[[297 243  49  49]]
[[300 246  45  45]
 [274 242  54  54]]
[[296 241  50  50]]
[[279 248  40  40]
 [298 242  48  48]]
[[299 243  48  48]
 [277 245  49  49]]
[[275 241  54  54]]
[[274 240  54  54]]
[[281 242  48  48]]
()
()
[[281 245  50  50]
 [538 334  37  37]]
[[280 247  47  47]]
[[300 241  47  47]
 [279 246  47  47]]
[[279 247  48  48]]
[[279 245  49  49]]
()
[[296 240  50  50]]
()
[[277 244  49  49]
 [296 241  50  50]]
[[280 246  44  44]]
[[294 240  52  52]]
[[279 246  43  43]]
()
()
()
[[281 248  41  41]]
[[283 249  41  41]]
[[282 250  40  40]]
[[279 244  48  48]]
[[279 244  48  48]]
[[278 244  49  49]]
[[278 243  48  48]]
[[276 242  51  51]]
[[279 244  47  47]]
[[280 244  46  46]]
()
[[278 242  54  54]]
()
[[280 245  46  46]]
[[284 246  40  40]]

In [ ]:
cv2.waitKey(0)
cap.release()